# combination right and left
upper_body: 
#right_id : left_id
  1 : 2
  3 : 4
  5 : 6
  7 : 8
  9 : 10
  11 : 12
  13 : 14
  30 : 31
lower_body:
  15 : 16
  17 : 18
  19 : 20
  21 : 22
  23 : 24
  25 : 26
  